baseurl: http://www.dev.scottlogic.co.uk/blog
permalink: /:year/:month/:day/:title.html
safe: true
lsi: false

debug: false

pygments: true
markdown: maruku

destination: _site-safe
include: [.htaccess]
exclude: [_migration]

active-authors: [aaylett, ceberhardt, cgrant, cprice, godds, lpage, mrhodes, nhemley, nwolverson, rbaxter, shall, shogarth]
authors:
    ceberhardt:
        name: Colin Eberhardt
        gravatar: 458f2e0d08d4114f8b323798cfea141d
    cprice:
        name: Chris Price
        gravatar: b6fe36176ec7c9475374a5cd3b7bef1a
    lpage:
        name: Luke Page
    aaylett:
        name: Andrew Aylett
        gravatar: 279455275f7e4f69b0759fec26130c01
    rbaxter:
        name: Rolf Baxter
    jcardy:
        name: Jonathan Cardy
    cgrant:
        name: Chris Grant
    shall:
        name: Steven Hall
        gravatar: 30187520d3181c674d7b7ecbcbbf48b1
    nhemley:
        name: Nicholas Hemley
    godds:
        name: Graham Odds
        gravatar: 3f5e6c753071c6a41f7f1dbb89daeb3b
    gorosz:
        name: Gergely Orosz
        gravatar: 4de0bd0d87ade9cac3a76609a80c9af3
    mperrin:
        name: Mike Perrin
    mrhodes:
        name: Mark Rhodes
        gravatar: fd23036b365ac4d5492207da6dbe0248
    shogarth:
        name: Sam Hogarth
        gravatar: d4534a4d64ddf89c318221d9f0e766da
    nwolverson:
        name: Nicholas Wolverson
        gravatar: c2fa082fa1ffbab1293262c599d459fb
