baseurl: http://sl-ws-069.scottlogic.co.uk/website/scottlogic-website-blogs/_site-safe
permalink: /:year/:month/:day/:title.html
safe: true
lsi: false

debug: true

pygments: true
markdown: maruku

destination: _site-safe
include: [.htaccess]
exclude: [_migration]
paginate: 10

author:
    ceberhardt:
        name: Colin Eberhardt
    cprice:
        name: Chris Price
    lpage:
        name: Luke Page
    aaylett:
        name: Andrew Aylett
    rbaxter:
        name: Rolf Baxter
    jcardy:
        name: Jonathan Cardy
    cgrant:
        name: Chris Grant
    shall:
        name: Steven Hall
    nhemley:
        name: Nicholas Hemley
    godds:
        name: Graham Odds
    gorosz:
        name: Gergely Orosz
    mperrin:
        name: Mike Perrin
    mrhodes:
        name: Mark Rhodes
    shogarth:
        name: Sam Hogarth
    nwolverson:
        name: Nicholas Wolverson
