name: Scott Logic
description: This feed is brought to you by Scott Logic's team of technical authors and bloggers, covering topics including HTML5, iOS, C#, process, UX and practically anything else relating to software development.
canonical:
    url: http://blog.scottlogic.com
scottlogic:
    url: http://www.scottlogic.com
scottlogicdisqusurl: https://disqus.com/home/discussion/scottlogic/
permalink: /:year/:month/:day/:title.html
safe: true
twitter_handle: Scott_Logic

kramdown:
    input: kramdown

paginate: 20

excerpt_separator: ""

exclude:
    - checkdups
    - CNAME
    - create-blog-post.sh
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - scss
    - node_modules
    - package.json
    - README.md
    - .spelling
    # N.B. Not all scripts are excluded, as some are directly referenced, because:
    # - jquery-1.9.1.js - some posts make use of this
    # - disqus-comment-thread.js - only required on the post pages
    - scripts/disqus-comment-count.js
    - scripts/jquery-1.9.1.js
    - scripts/jquery.jscroll-2.2.4.js
    - scripts/tweet.js
    - scripts/search.js


# For local use only
# If building the site locally, you won't have access to the site.github namespace
# Uncomment the lines below to have access to these variables when building locally

#github:
#    url: http://blog.scottlogic.com
#    owner_name: ScottLogic
#

# Uncomment the lines below to enable requried Jekyll plugins when building locally.
#gems:
#    - jekyll-gist
#    - jekyll-paginate
#whitelist:
#    - jekyll-gist
#    - jekyll-paginate
