name: Scott Logic
description: This feed is brought to you by Scott Logic's team of technical authors and bloggers, covering topics including HTML5, iOS, C#, process, UX and practically anything else relating to software development.
baseurl: /blog
siteurl: http://www.scottlogic.com
scottlogicdisqusurl: http://scottlogic.disqus.com
permalink: /:year/:month/:day/:title.html
safe: true
lsi: false

debug: false

pygments: true
markdown: maruku

destination: _site-safe
include: [.htaccess]
exclude: [_migration, checkdups, post-receive, README.txt, redirect_list.html,create-blog-post.sh]

active-authors: [aaylett, amorgan, ceberhardt, cgrant, cprice, dkerr, godds, jphillpotts, lpage, mrhodes, nhemley, nwolverson, rbaxter, rwilliams, sduncan, shall, shogarth, dmcnamee, dgorst, alee, dthomas]
authors:
    labs:
        name: Scott Logic Labs
    ceberhardt:
        name: Colin Eberhardt
        email: ceberhardt@scottlogic.com
        gravatar: 458f2e0d08d4114f8b323798cfea141d
        author-summary: A coding addict, dividing my time between iOS, C#, JavaScript and everything else. <br/><br/><a href="https://twitter.com/ColinEberhardt">@ColinEberhardt</a> <a href="https://plus.google.com/u/0/104181672098184856535" rel="author">Google+</a> <br/><br/>CTO @ <a href="http://www.shinobicontrols.com">ShinobiControls</a>
        feed-description: Colin Eberhardt's Technology Adventures
    cprice:
        name: Chris Price
        email: cprice@scottlogic.com
        gravatar: b6fe36176ec7c9475374a5cd3b7bef1a
        author-summary: <a href="https://twitter.com/100pxls">@100pxls</a><br/><a href="https://plus.google.com/u/0/114347034265773524402" rel="author">Google+</a>
    lpage:
        name: Luke Page
        email: lpage@scottlogic.com
    aaylett:
        name: Andrew Aylett
        email: aaylett@scottlogic.com
        gravatar: 279455275f7e4f69b0759fec26130c01
        author-summary: '<a href="https://twitter.com/aaylett">Twitter: @aaylett</a><br/><a href="https://plus.google.com/117103827242094116619">Google+</a>'
    rbaxter:
        name: Rolf Baxter
        email: rbaxter@scottlogic.com
        gravatar: b75269f75824889e8569f35d73ddd32b
    jcardy:
        name: Jonathan Cardy
    cgrant:
        name: Chris Grant
        email: cgrant@scottlogic.com
        gravatar: 7ed1a4b5f686f58db97862a26d38d30f
    shall:
        name: Steven Hall
        email: stevenhall@scottlogic.com
        gravatar: 30187520d3181c674d7b7ecbcbbf48b1
    nhemley:
        name: Nicholas Hemley
        email: nhemley@scottlogic.com
    godds:
        name: Graham Odds
        email: godds@scottlogic.com
        gravatar: 3f5e6c753071c6a41f7f1dbb89daeb3b
        author-summary: Designer and developer working across desktop, web and mobile, with a particular taste for data visualisation.<br/><a href="https://twitter.com/g_odds">@g_odds</a><br/><a href="https://plus.google.com/u/0/106838695703708413394" rel="author">Google+</a>
        feed-description: Graham Odds is a designer and developer working across desktop, web and mobile, with a particular taste for data visualisation.  He likes to educate coders about the concept of users and artists about the reality of technology, or just rant and rave at whoever will read his blog.
    mperrin:
        name: Mike Perrin
    mrhodes:
        name: Mark Rhodes
        email: mrhodes@scottlogic.com
        gravatar: fd23036b365ac4d5492207da6dbe0248
    shogarth:
        name: Sam Hogarth
        email: shogarth@scottlogic.com
        gravatar: d4534a4d64ddf89c318221d9f0e766da
        author-summary: Frequently found developing Android applications, playing with web technologies and musing about patterns and process.
        feed-description: Sam Hogarth is a developer working primarily with web technologies, with a side-interest in Android development.
    nwolverson:
        name: Nicholas Wolverson
        email: nwolverson@scottlogic.com
        gravatar: c2fa082fa1ffbab1293262c599d459fb
    jphillpotts:
        name: James Phillpotts
        email: jphillpotts@scottlogic.com
        gravatar: 6fdbb823b145fb77ecd8b8bfc442fb95
    tbaker:
        name: Tom Baker
        email: tbaker@scottlogic.com
    dkerr:
        name: Dean Kerr
        email: dkerr@scottlogic.com
    sduncan:
        name: Simon Duncan
        email: sduncan@scottlogic.co.uk
        gravatar: 0f765c3e99ff8441cf0d0f60aed9634b
        author-summary: UX designer. Arduino & physical computing enthusiast. Likes hip hop and 30 minute drone pieces.<br/><br/><a href="https://twitter.com/simonduncan">@simonduncan</a>
        feed-description: Simon Duncan is a UX designer, particularly interested in interaction design and information architecture. These are some of his thoughts.
    rwilliams:
        name: Robat Williams
        email: rwilliams@scottlogic.co.uk
        gravatar: b2e17d98db06119a53fffd5666848871
        author-summary: <a href="https://twitter.com/_rwms">@_rwms</a><br/><a href="https://plus.google.com/u/0/111956836520400525467" rel="author">Google+</a>
    amorgan:
        name: Adam Morgan
        email: amorgan@scottlogic.co.uk
    ilopatkin:
        name: Ilya Lopatkin
        email: ilopatkin@scottlogic.co.uk
        gravatar: 8a4e1343172f9207ae1f73520e09d9c8
    dmcnamee:
        name: Daniel McNamee
        email: dmcnamee@scottlogic.com
        gravatar: a764bd37e5ba2ba9305fc4d0c8b67aa7
        author-summary: Tester. Photographer. <br/><br/><a href="https://twitter.com/demcnamee">twitter</a><br/><a href="https://www.google.com/+DanielMcNamee">google+</a>
        feed-description: Daniel is a senior test engineer and exponent of rapid software testing.
    dgorst:
        name: Dan Gorst
        email: dgorst@scottlogic.com
        gravatar: bd790d492bb45a531a39adbbb1b3274c
    alee:
        name: Andy Lee
        email: alee@scottlogic.com
        gravatar: f585309d8acd3635c90a9298ea3d46e1
    dthomas:
        name: David Thomas
        email: dthomas@scottlogic.co.uk
        gravatar: cee30211dde61525a902ad9f05d8e56e
