auto: false
server: false
lsi: false
baseurl: /
destination: ~/public_html/blog/
paginate: 10
exclude: [_migration]
name: Scott Logic
description: Financial Software Development
disqus_shortname: jekyllplayground
disqus-site-url: http://chrisprice.github.com/jekyll-playground/
debug: false
safe: true
lsi: false
pygments: true
markdown: maruku
include: [.htaccess]
rssimage_url: XXX
rssimage_height: XXX
rssimage_width: XXX
language: en