baseurl: http://www.dev.scottlogic.co.uk/blog 
permalink: /:year/:month/:day/:title.html
safe: true
lsi: false

debug: true

pygments: true
markdown: maruku

destination: _site-safe
include: [.htaccess]
exclude: [_migration]

active-authors: [aaylett, ceberhardt, cgrant, cprice, godds, lpage, mrhodes, nhemley, nwolverson, rbaxter, shall, shogarth]
authors:
    ceberhardt:
        name: Colin Eberhardt
        gravatar: 458f2e0d08d4114f8b323798cfea141d
    cprice:
        name: Chris Price
        gravatar: b6fe36176ec7c9475374a5cd3b7bef1a
    lpage:
        name: Luke Page
    aaylett:
        name: Andrew Aylett
    rbaxter:
        name: Rolf Baxter
    jcardy:
        name: Jonathan Cardy
    cgrant:
        name: Chris Grant
    shall:
        name: Steven Hall
    nhemley:
        name: Nicholas Hemley
    godds:
        name: Graham Odds
        gravatar: 3f5e6c753071c6a41f7f1dbb89daeb3b
    gorosz:
        name: Gergely Orosz
    mperrin:
        name: Mike Perrin
    mrhodes:
        name: Mark Rhodes
    shogarth:
        name: Sam Hogarth
        gravatar: d4534a4d64ddf89c318221d9f0e766da
    nwolverson:
        name: Nicholas Wolverson
