version: 2
jobs:
    spellcheck:
        docker:
            - image: circleci/node:10.9-browsers
        steps:
            - checkout
            - restore_cache:
                key: v0-blog-npm-cache-{{ checksum "package-lock.json" }}
            - run:
                command: |
                    npm install
            - save_cache:
                key: v0-blog-npm-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - run: npm test
workflows:
    version: 2
    build_and_test:
        jobs:
            - spellcheck